### PR TITLE
 Request for code review: Building with Active Record

### PR DESCRIPTION
**Pull request by marcoshdezcam**
# Micro Reddit
In this project we implemented the following: 
- Created the data models for User, Post, and Comment. 
- Added validators to attributes
- Created relationships and associations

### 👤 Authors
@marcoshdezcam and @che30

### 🔧 Built With
- Ruby
- Gitflow Workflow

Thank you for taking the time to review our code! 💐

### CODE REVIEW

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Request Changes :red_circle:
### You've done great work so far but we still missing some features to proceed to the next project.
- [x] **`.gitignore:`** Please add .gitignore file with the fallowing configuration 
 ```
 # Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# Ignore uploaded files in development.
/storage/*
!/storage/.keep

/public/assets
.byebug_history

# Ignore master key for decrypting credentials and more.
/**/*.key

/public/packs
/public/assets
/public/packs-test
/node_modules
/yarn-error.log
yarn-debug.log*
.yarn-integrity

/public/packs
/public/packs-test
/node_modules
/yarn-error.log
yarn-debug.log*
.yarn-integrity
 ```
> make sure you remove all the file listed here from your current git-flow

- [ ] **Comments:** 
  - [x] Should Validated `body`
  - [x] Should Have Associations to User `belongs_to :user`
  - [x] Should Have Associations to Post `belongs_to :post`

- [ ] **Posts:**
  - [x] Should Have Associations to Comments `has_many :comments`

- [ ] **User:**
  - [x] Should Have Associations to Comments `has_many :comments`

# Good Luck, :+1:  Happy Coding :computer: :nerd_face:

**Comment by che30** [comment]
All changes implemented as required

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [x] Lets remove node_modules from git history https://stackoverflow.com/a/59250427.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by che30** [comment]
node module removed

**Review by trekab — APPROVED** [review]
Added association as required

**Pull request merged**
